apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml
