apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType : Prefix
        backend:
          service:
            name: sample-service
            port:
              number: 4000

# - host: localhost-testing. Seems that wsl resets /etc/hosts after every restart. 
