apiVersion: apps/v1
kind: Deployment
metadata:
  name:  sample-pod-deployment
  labels:
    app:  sample-pod
spec:
  selector:
    matchLabels:
      app: sample-pod
  replicas: 5
  template:
    metadata:
      labels:
        app:  sample-pod
    spec:
      containers:
      - name:  sample-pod
        image:  juanpablosgu/hello-world-app:latest
        ports:
        - containerPort: 4000
