replicaCount: 2

service:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000

ingress:
  hosts:
    - host: localhost-dev
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: helm-app-api-service
              port:
                number: 80

